#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  database: bldrcl
  username: root
  password:
  host: localhost
  pool: 20
  wait_timeout: 15
production: development
