#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  database: bldrcl
  username: postgres

production:
  adapter: postgresql
  database: bldrcl
  username: postgres
